server:
  port: 1105
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/recipe
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations=classpath: src/main/resources/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ?????sql??
    map-underscore-to-camel-case: true #驼峰映射
  type-aliases-package: com.hh.recipe.domain  # 设置别名扫描的包路径
jwt:
  token:
    tokenExpiration: 1200000 #有效时间,单位分钟
    tokenSignKey: recipeHh1105   #用于生成token签名的密钥
